name: Build and Test Anomaly detection
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  spotless:
    if: github.repository == 'opensearch-project/anomaly-detection'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Spotless Check
        run: ./gradlew spotlessCheck

  Build-ad-windows:
    needs: spotless
    strategy:
      matrix:
        java: [21, 25]
    name: Build and Test Anomaly Detection Plugin on Windows
    runs-on: windows-latest
    env:
      JENKINS_URL: build.ci.opensearch.org
    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Checkout Anomaly Detection
        uses: actions/checkout@v6

      - name: Build and Run Tests
        run: |
          ./gradlew build -x spotlessJava
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - name: Multi Nodes Integration Testing
        run: |
          ./gradlew integTest -PnumNodes=3

  Build-ad-linux:
    needs: [Get-CI-Image-Tag, spotless]
    strategy:
      matrix:
        java: [21, 25]
      fail-fast: false
    name: Build and Test Anomaly detection Plugin on Linux
    runs-on: ubuntu-latest
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}

    env:
      JENKINS_URL: build.ci.opensearch.org

    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Checkout AD
        uses: actions/checkout@v6

      - name: Assemble / build / mavenlocal / integTest
        run: |
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c "./gradlew assemble &&
                               ./gradlew build -x spotlessJava &&
                               ./gradlew publishToMavenLocal &&
                               ./gradlew integTest -PnumNodes=3"

  Build-ad-macos:
    needs: spotless
    strategy:
      matrix:
        java: [21, 25]
      fail-fast: false

    name: Build and Test Anomaly detection Plugin on MacOS
    runs-on: macos-15-intel
    env:
      JENKINS_URL: build.ci.opensearch.org

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Checkout AD
        uses: actions/checkout@v6

      - name: Assemble anomaly-detection
        run: |
          ./gradlew assemble
      - name: Build and Run Tests
        run: |
          ./gradlew build -x spotlessJava
      # coverage.gradle is only applied in single local node test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal
      - name: Multi Nodes Integration Testing
        run: |
          ./gradlew integTest -PnumNodes=3
